server: irc.synirc.net
port: 6667
nick: clearbot
username: clearbot
realName: C++ Lua Extensible Architecture Reactive Bot
password: myPassword
owner: othi
modes: +B 
api_keys:
  google: 1234
  wunderground: 01c359b7f7bcf231
